name: CI

on:
  push:
    branches: [ main, pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: apt update
      run: sudo apt-get update

    - name: install dependencies
      run: sudo apt-get install -y cmake make g++ curl zip unzip ninja-build automake libtool build-essential libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev

    - name: Install vcpkg (clone)
      run: git clone https://github.com/microsoft/vcpkg.git

    - name: Add Ninja to PATH
      run: echo "/usr/bin/ninja" >> $GITHUB_PATH

    - name: Verify Ninja path
      run: echo $PATH

    - name: Configure CMake
      run: cmake -G Ninja --preset linux

    - name: Build
      run: cd build && cmake .. && cmake --build .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build-artifacts
        path: build/

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name : install cmake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' && refreshenv
    - name: install vcpkg
      run: git clone https://github.com/microsoft/vcpkg.git
    - name: run vcpkg bootstrap
      run: .\vcpkg\bootstrap-vcpkg.bat

    - name: Configure CMake
      run: cmake --preset windows-static

    - name: Build
      run: cd build && cmake .. && cmake --build .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build-artifacts
        path: build/

  download-artifacts:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Download Linux build artifacts
      if: needs.build-linux.result == 'success'
      uses: actions/download-artifact@v2
      with:
        name: linux-build-artifacts
        path: linux-build/

    - name: Download Windows build artifacts
      if: needs.build-windows.result == 'success'
      uses: actions/download-artifact@v2
      with:
        name: windows-build-artifacts
        path: windows-build/