name: CI

on:
  push:
    branches: [ main, pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++ curl zip unzip ninja-build automake libtool build-essential
        git clone https://github.com/microsoft/vcpkg.git

    - name: Configure CMake
      run: cmake --preset linux

    - name: Build
      run: cmake --build build

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' && refreshenv
        git clone https://github.com/microsoft/vcpkg.git

    - name: Configure CMake
      run: cmake --preset windows-static

    - name: Build
      run: cmake --build build