name: Mirror

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}