name: Mirror

on:
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run check_format script
      run: ./Scripts/check_format.sh
    
    - name: Display error message on failure
      if: failure()
      run: echo "Code formatting issues detected. Please run './Scripts/format_all.sh' to fix them."

  build:
    runs-on: ubuntu-latest
    needs: check-format # If the check-format job fails, the build mirror job will not run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}